subzy -targets 1688.com.txt --hide_fails
subzy -targets 18f.gov.txt --hide_fails
subzy -targets 4cdn.org.txt --hide_fails
subzy -targets 4chan.org.txt --hide_fails
subzy -targets 8x8.com.txt --hide_fails
subzy -targets 8x8.spot.txt --hide_fails
subzy -targets 8x8.vc.txt --hide_fails
subzy -targets 9lives.be.txt --hide_fails
subzy -targets accengage.net.txt --hide_fails
subzy -targets accountkit.com.txt --hide_fails
subzy -targets achmea.com.au.txt --hide_fails
subzy -targets achmea.nl.txt --hide_fails
subzy -targets acorns.com.txt --hide_fails
subzy -targets actify.nl.txt --hide_fails
subzy -targets adafruit.com.txt --hide_fails
subzy -targets adafruitdaily.com.txt --hide_fails
subzy -targets aetkasmart.de.txt --hide_fails
subzy -targets aips-internal.com.txt --hide_fails
subzy -targets aips-services.com.txt --hide_fails
subzy -targets airbnb.app.txt --hide_fails
subzy -targets airbnb-aws.com.txt --hide_fails
subzy -targets airbnbcitizen.com.txt --hide_fails
subzy -targets airbnb.com.txt --hide_fails
subzy -targets airmap.com.txt --hide_fails
subzy -targets airship.com.txt --hide_fails
subzy -targets airship.eu.txt --hide_fails
subzy -targets airtable.com.txt --hide_fails
subzy -targets aiven.io.txt --hide_fails
subzy -targets alditalk-kundenbetreuung.de.txt --hide_fails
subzy -targets algolia.com.txt --hide_fails
subzy -targets algolianet.com.txt --hide_fails
subzy -targets algolia.net.txt --hide_fails
subzy -targets alibabacloud.com.txt --hide_fails
subzy -targets alibaba.com.txt --hide_fails
subzy -targets alibaba-inc.com.txt --hide_fails
subzy -targets aliexpress.com.txt --hide_fails
subzy -targets alimama.com.txt --hide_fails
subzy -targets aliyun.com.txt --hide_fails
subzy -targets aliyun-inc.com.txt --hide_fails
subzy -targets allegrosandbox.pl.txt --hide_fails
subzy -targets amazon.co.jp.txt --hide_fails
subzy -targets amazon.com.txt --hide_fails
subzy -targets amazon.co.uk.txt --hide_fails
subzy -targets amazon.de.txt --hide_fails
subzy -targets amazon.fr.txt --hide_fails
subzy -targets amitree.com.txt --hide_fails
subzy -targets am.ru.txt --hide_fails
subzy -targets app.mobile.txt --hide_fails
subzy -targets apptimize.com.txt --hide_fails
subzy -targets apptimize.eu.txt --hide_fails
subzy -targets apsis.com.txt --hide_fails
subzy -targets areeba.com.gn.txt --hide_fails
subzy -targets arkoselabs.com.txt --hide_fails
subzy -targets arlo.com.txt --hide_fails
subzy -targets asnbank.nl.txt --hide_fails
subzy -targets astaro.at.txt --hide_fails
subzy -targets astaro.ch.txt --hide_fails
subzy -targets astaro.com.txt --hide_fails
subzy -targets astaro.de.txt --hide_fails
subzy -targets astaro.info.txt --hide_fails
subzy -targets astaro.net.txt --hide_fails
subzy -targets astaro.org.txt --hide_fails
subzy -targets astrogaming.com.txt --hide_fails
subzy -targets atairbnb.com.txt --hide_fails
subzy -targets atlassian.com.txt --hide_fails
subzy -targets atlassian.net.txt --hide_fails
subzy -targets atspotify.com.txt --hide_fails
subzy -targets att.com.txt --hide_fails
subzy -targets auspost.com.au.txt --hide_fails
subzy -targets authy.com.txt --hide_fails
subzy -targets auvik.com.txt --hide_fails
subzy -targets averoachmea.nl.txt --hide_fails
subzy -targets avito.ru.txt --hide_fails
subzy -targets ayco.com.txt --hide_fails
subzy -targets ayyildiz.de.txt --hide_fails
subzy -targets backblazeb2.com.txt --hide_fails
subzy -targets backblaze.com.txt --hide_fails
subzy -targets backstage.io.txt --hide_fails
subzy -targets backtrack-linux.org.txt --hide_fails
subzy -targets badoocdn.com.txt --hide_fails
subzy -targets badoo.com.txt --hide_fails
subzy -targets base.be.txt --hide_fails
subzy -targets base.de.txt --hide_fails
subzy -targets basicattentiontoken.org.txt --hide_fails
subzy -targets bbpress.org.txt --hide_fails
subzy -targets bentley.com.txt --hide_fails
subzy -targets berush.com.txt --hide_fails
subzy -targets betfair.com.txt --hide_fails
subzy -targets betfair.es.txt --hide_fails
subzy -targets betfair.exchange.txt --hide_fails
subzy -targets betfair.it.txt --hide_fails
subzy -targets betfair.ro.txt --hide_fails
subzy -targets betfair.se.txt --hide_fails
subzy -targets better.com.txt --hide_fails
subzy -targets betterscience.org.txt --hide_fails
subzy -targets bezcenneniespodzianki.pl.txt --hide_fails
subzy -targets bigbank.ee.txt --hide_fails
subzy -targets bigbank.eu.txt --hide_fails
subzy -targets bigbank.fi.txt --hide_fails
subzy -targets bigbank.lt.txt --hide_fails
subzy -targets bigbank.lv.txt --hide_fails
subzy -targets bimeanalytics.com.txt --hide_fails
subzy -targets bime.io.txt --hide_fails
subzy -targets binance.com.txt --hide_fails
subzy -targets binance.co.ug.txt --hide_fails
subzy -targets binance.je.txt --hide_fails
subzy -targets binance.org.txt --hide_fails
subzy -targets binance.sg.txt --hide_fails
subzy -targets binance.us.txt --hide_fails
subzy -targets binary.com.txt --hide_fails
subzy -targets bingo.com.txt --hide_fails
subzy -targets bitaccessbtm.com.txt --hide_fails
subzy -targets bitdefender.com.txt --hide_fails
subzy -targets bitdefender.net.txt --hide_fails
subzy -targets bitdiscovery.com.txt --hide_fails
subzy -targets bitgo.com.txt --hide_fails
subzy -targets bitmex.com.txt --hide_fails
subzy -targets bitmoji.com.txt --hide_fails
subzy -targets bitstrips.com.txt --hide_fails
subzy -targets bitwala.app.txt --hide_fails
subzy -targets bitwala.com.txt --hide_fails
subzy -targets bitwarden.com.txt --hide_fails
subzy -targets blackhistoryisnow.com.txt --hide_fails
subzy -targets blau.de.txt --hide_fails
subzy -targets blauworld.de.txt --hide_fails
subzy -targets blend.com.txt --hide_fails
subzy -targets blendlabs.com.txt --hide_fails
subzy -targets blgwonen.nl.txt --hide_fails
subzy -targets blockchain.com.txt --hide_fails
subzy -targets blockchain.info.txt --hide_fails
subzy -targets blogger.com.txt --hide_fails
subzy -targets bluejeans.com.txt --hide_fails
subzy -targets bluesnap.com.txt --hide_fails
subzy -targets bluetarp.com.txt --hide_fails
subzy -targets bmw.de.txt --hide_fails
subzy -targets bmw-motorrad.de.txt --hide_fails
subzy -targets bokun.com.txt --hide_fails
subzy -targets bolstr.com.txt --hide_fails
subzy -targets bookingholdings.com.txt --hide_fails
subzy -targets boomi.com.txt --hide_fails
subzy -targets booth.pm.txt --hide_fails
subzy -targets boozt.com.txt --hide_fails
subzy -targets booztlet.com.txt --hide_fails
subzy -targets bplans.com.txt --hide_fails
subzy -targets braintree-api.com.txt --hide_fails
subzy -targets braintreegateway.com.txt --hide_fails
subzy -targets braintreepayments.com.txt --hide_fails
subzy -targets braintree.tools.txt --hide_fails
subzy -targets brave.com.txt --hide_fails
subzy -targets breadcrumb.com.txt --hide_fails
subzy -targets briefe.io.txt --hide_fails
subzy -targets buddypress.org.txt --hide_fails
subzy -targets buffer.com.txt --hide_fails
subzy -targets bugbountyguide.com.txt --hide_fails
subzy -targets bugcrowd.com.txt --hide_fails
subzy -targets bugpoc.com.txt --hide_fails
subzy -targets bugpoc.ninja.txt --hide_fails
subzy -targets buildseries.com.txt --hide_fails
subzy -targets builtbygirls.com.txt --hide_fails
subzy -targets bunq.com.txt --hide_fails
subzy -targets butlerfortrello.com.txt --hide_fails
subzy -targets byairbnb.com.txt --hide_fails
subzy -targets byspotify.com.txt --hide_fails
subzy -targets byteoversea.com.txt --hide_fails
subzy -targets cafebazaar.ir.txt --hide_fails
subzy -targets caffeine.tv.txt --hide_fails
subzy -targets cainbrothers.com.txt --hide_fails
subzy -targets cainiao.com.txt --hide_fails
subzy -targets callstats.io.txt --hide_fails
subzy -targets canon.com.txt --hide_fails
subzy -targets canva.cn.txt --hide_fails
subzy -targets canva.com.txt --hide_fails
subzy -targets capitalone360.com.txt --hide_fails
subzy -targets capitalonebank.com.txt --hide_fails
subzy -targets capitalonecards.com.txt --hide_fails
subzy -targets capitalonecareers.co.uk.txt --hide_fails
subzy -targets capitalone.ca.txt --hide_fails
subzy -targets capitalone.com.txt --hide_fails
subzy -targets capitalone.co.uk.txt --hide_fails
subzy -targets capitalone.tz.txt --hide_fails
subzy -targets cashier.ru.txt --hide_fails
subzy -targets cash.me.txt --hide_fails
subzy -targets casinohuone.com.txt --hide_fails
subzy -targets casper.com.txt --hide_fails
subzy -targets casper.tools.txt --hide_fails
subzy -targets cbhq.net.txt --hide_fails
subzy -targets centraalbeheer.nl.txt --hide_fails
subzy -targets centrify.com.txt --hide_fails
subzy -targets certsy.com.txt --hide_fails
subzy -targets certsynonprod.com.txt --hide_fails
subzy -targets cfptime.org.txt --hide_fails
subzy -targets chain.link.txt --hide_fails
subzy -targets challonge.com.txt --hide_fails
subzy -targets chaturbate.com.txt --hide_fails
subzy -targets checkpoint.com.txt --hide_fails
subzy -targets cirrusinsight.com.txt --hide_fails
subzy -targets cirruspath.com.txt --hide_fails
subzy -targets cisco.com.txt --hide_fails
subzy -targets citypossible.com.txt --hide_fails
subzy -targets clario.co.txt --hide_fails
subzy -targets claritymoney.com.txt --hide_fails
subzy -targets clausestaging.com.txt --hide_fails
subzy -targets clickup.com.txt --hide_fails
subzy -targets clio.com.txt --hide_fails
subzy -targets closetheplaygap.com.txt --hide_fails
subzy -targets cloudflareaccess.com.txt --hide_fails
subzy -targets cloudflare.com.txt --hide_fails
subzy -targets cloudflareworkers.com.txt --hide_fails
subzy -targets cloud.gov.txt --hide_fails
subzy -targets cloudinary.com.txt --hide_fails
subzy -targets cloudways.com.txt --hide_fails
subzy -targets cobinhood.com.txt --hide_fails
subzy -targets cobinhood.exchange.txt --hide_fails
subzy -targets coda.io.txt --hide_fails
subzy -targets codefi.network.txt --hide_fails
subzy -targets code.gov.txt --hide_fails
subzy -targets codeigniter.com.txt --hide_fails
subzy -targets cognitiveperformer.com.txt --hide_fails
subzy -targets coinbase.com.txt --hide_fails
subzy -targets coinbase.pro.txt --hide_fails
subzy -targets coloros.com.txt --hide_fails
subzy -targets comcast.com.txt --hide_fails
subzy -targets companyhub.com.txt --hide_fails
subzy -targets connectis.com.txt --hide_fails
subzy -targets constantcontact.com.txt --hide_fails
subzy -targets contact-sys.com.txt --hide_fails
subzy -targets converse.com.txt --hide_fails
subzy -targets copper.com.txt --hide_fails
subzy -targets counter-strike.net.txt --hide_fails
subzy -targets coursera.org.txt --hide_fails
subzy -targets c-point.be.txt --hide_fails
subzy -targets crawlera.com.txt --hide_fails
subzy -targets creditkarma.ca.txt --hide_fails
subzy -targets creditkarma.com.txt --hide_fails
subzy -targets criticalstack.com.txt --hide_fails
subzy -targets crowdin.com.txt --hide_fails
subzy -targets crowdstrike.com.txt --hide_fails
subzy -targets crowdstrike.org.txt --hide_fails
subzy -targets cruisecritic.com.txt --hide_fails
subzy -targets crypto.com.txt --hide_fails
subzy -targets cryptography.io.txt --hide_fails
subzy -targets cryptojourney.com.txt --hide_fails
subzy -targets ct0.app.txt --hide_fails
subzy -targets curve.app.txt --hide_fails
subzy -targets curve.com.txt --hide_fails
subzy -targets cuv-prod.app.txt --hide_fails
subzy -targets cuvva.com.txt --hide_fails
subzy -targets cuvva.co.txt --hide_fails
subzy -targets cyberoam.com.txt --hide_fails
subzy -targets d2evh2mef3r450.cloudfront.net.txt --hide_fails
subzy -targets dailymotionadvertising.com.txt --hide_fails
subzy -targets dailymotion.com.txt --hide_fails
subzy -targets dashlane.com.txt --hide_fails
subzy -targets data.gov.txt --hide_fails
subzy -targets datastax.com.txt --hide_fails
subzy -targets d-cd.net.txt --hide_fails
subzy -targets defriesland.nl.txt --hide_fails
subzy -targets delight.im.txt --hide_fails
subzy -targets deliveroo-data.io.txt --hide_fails
subzy -targets deliveroo-data.net.txt --hide_fails
subzy -targets deliveroo-data-test.io.txt --hide_fails
subzy -targets deliveroo-streams.net.txt --hide_fails
subzy -targets delivery-club.ru.txt --hide_fails
subzy -targets dell.com.txt --hide_fails
subzy -targets dellemc.com.txt --hide_fails
subzy -targets delltechnologies.com.txt --hide_fails
subzy -targets deribit.com.txt --hide_fails
subzy -targets devmaximum.com.txt --hide_fails
subzy -targets devolksbank.nl.txt --hide_fails
subzy -targets didichuxing.com.txt --hide_fails
subzy -targets didiglobal.com.txt --hide_fails
subzy -targets didiyun.com.txt --hide_fails
subzy -targets digitalocean.com.txt --hide_fails
subzy -targets digitaloceanspaces.com.txt --hide_fails
subzy -targets dingtalk.com.txt --hide_fails
subzy -targets directly.com.txt --hide_fails
subzy -targets discord.com.txt --hide_fails
subzy -targets djelectro.me.txt --hide_fails
subzy -targets djicdn.com.txt --hide_fails
subzy -targets dji.com.txt --hide_fails
subzy -targets dji.net.txt --hide_fails
subzy -targets djiservice.org.txt --hide_fails
subzy -targets djivideos.com.txt --hide_fails
subzy -targets dmcdn.net.txt --hide_fails
subzy -targets dm.gg.txt --hide_fails
subzy -targets dnspod.cn.txt --hide_fails
subzy -targets doaction.org.txt --hide_fails
subzy -targets doesmydogmissme.com.txt --hide_fails
subzy -targets donationalerts.com.txt --hide_fails
subzy -targets donationalerts.ru.txt --hide_fails
subzy -targets dota2.com.txt --hide_fails
subzy -targets dovecot.org.txt --hide_fails
subzy -targets drive2.ru.txt --hide_fails
subzy -targets driveuconnect.com.txt --hide_fails
subzy -targets driveuconnect.eu.txt --hide_fails
subzy -targets dropbox.com.txt --hide_fails
subzy -targets dropboxforum.com.txt --hide_fails
subzy -targets duckduckgo.com.txt --hide_fails
subzy -targets dxi.eu.txt --hide_fails
subzy -targets dynoquant.com.txt --hide_fails
subzy -targets easycontactnow.com.txt --hide_fails
subzy -targets eccouncil.org.txt --hide_fails
subzy -targets ecobee.com.txt --hide_fails
subzy -targets edmodo.com.txt --hide_fails
subzy -targets edoverflow.com.txt --hide_fails
subzy -targets einfachprepaid.de.txt --hide_fails
subzy -targets eleganthotels.com.txt --hide_fails
subzy -targets elvenar.com.txt --hide_fails
subzy -targets emc.com.txt --hide_fails
subzy -targets endlcdn.site.txt --hide_fails
subzy -targets endomondo.com.txt --hide_fails
subzy -targets engadget.com.txt --hide_fails
subzy -targets engelvoelkers.com.txt --hide_fails
subzy -targets enspotify.com.txt --hide_fails
subzy -targets eobot.com.txt --hide_fails
subzy -targets equalizerproject.com.txt --hide_fails
subzy -targets eslint.org.txt --hide_fails
subzy -targets etsy.com.txt --hide_fails
subzy -targets etsypayments.com.txt --hide_fails
subzy -targets eurekosigorta.com.tr.txt --hide_fails
subzy -targets eurocross.com.txt --hide_fails
subzy -targets eventbrite.com.txt --hide_fails
subzy -targets evernote.com.txt --hide_fails
subzy -targets everynoise.com.txt --hide_fails
subzy -targets every.org.txt --hide_fails
subzy -targets evonik.com.txt --hide_fails
subzy -targets exchangemarketplace.com.txt --hide_fails
subzy -targets exodus.io.txt --hide_fails
subzy -targets exploit-db.com.txt --hide_fails
subzy -targets expressobutiolem.onion.txt --hide_fails
subzy -targets expressvpn.com.txt --hide_fails
subzy -targets extraordinariesonthemic.com.txt --hide_fails
subzy -targets faa.st.txt --hide_fails
subzy -targets facebook.com.txt --hide_fails
subzy -targets fair.com.txt --hide_fails
subzy -targets fair.engineering.txt --hide_fails
subzy -targets falcon-sandbox.com.txt --hide_fails
subzy -targets fanduel.com.txt --hide_fails
subzy -targets fanduel.design.txt --hide_fails
subzy -targets fb.com.txt --hide_fails
subzy -targets fb.me.txt --hide_fails
subzy -targets fbto.nl.txt --hide_fails
subzy -targets fdbox.net.txt --hide_fails
subzy -targets fedramp.gov.txt --hide_fails
subzy -targets fig.co.txt --hide_fails
subzy -targets files.com.txt --hide_fails
subzy -targets filezilla-project.org.txt --hide_fails
subzy -targets finra.org.txt --hide_fails
subzy -targets first.org.txt --hide_fails
subzy -targets fitbit.com.txt --hide_fails
subzy -targets fitstar.com.txt --hide_fails
subzy -targets flickr.com.txt --hide_fails
subzy -targets flipkart.com.txt --hide_fails
subzy -targets flocktory.com.txt --hide_fails
subzy -targets fonic.de.txt --hide_fails
subzy -targets fonic-mobile.de.txt --hide_fails
subzy -targets ford.com.txt --hide_fails
subzy -targets forecastapp.com.txt --hide_fails
subzy -targets forescoutcloud.net.txt --hide_fails
subzy -targets forescout.com.txt --hide_fails
subzy -targets forgeofempires.com.txt --hide_fails
subzy -targets fortmatic.com.txt --hide_fails
subzy -targets foxycart.com.txt --hide_fails
subzy -targets freebasics.com.txt --hide_fails
subzy -targets freepeopledirectory.com.txt --hide_fails
subzy -targets freshcaller.com.txt --hide_fails
subzy -targets freshchat.com.txt --hide_fails
subzy -targets freshconnect.io.txt --hide_fails
subzy -targets freshdesk.com.txt --hide_fails
subzy -targets freshmarketer.com.txt --hide_fails
subzy -targets freshping.io.txt --hide_fails
subzy -targets freshsales.io.txt --hide_fails
subzy -targets freshservice.com.txt --hide_fails
subzy -targets freshworks.com.txt --hide_fails
subzy -targets fuzzing-project.org.txt --hide_fails
subzy -targets fw-notify.net.txt --hide_fails
subzy -targets gamepind.com.txt --hide_fails
subzy -targets gcr.io.txt --hide_fails
subzy -targets geistguest.com.txt --hide_fails
subzy -targets genasys.tech.txt --hide_fails
subzy -targets gener8ads.com.txt --hide_fails
subzy -targets get8x8.com.txt --hide_fails
subzy -targets getbambu.com.txt --hide_fails
subzy -targets getharvest.com.txt --hide_fails
subzy -targets getmoneytree.com.txt --hide_fails
subzy -targets gilacorp.com.txt --hide_fails
subzy -targets gimlet.design.txt --hide_fails
subzy -targets gimletmedia.com.txt --hide_fails
subzy -targets githubapp.com.txt --hide_fails
subzy -targets github.com.txt --hide_fails
subzy -targets github.net.txt --hide_fails
subzy -targets gitlab.com.txt --hide_fails
subzy -targets gitter.im.txt --hide_fails
subzy -targets glassdoor.app.txt --hide_fails
subzy -targets glassdoor.com.txt --hide_fails
subzy -targets global.shop.txt --hide_fails
subzy -targets gmelius.com.txt --hide_fails
subzy -targets gnip.com.txt --hide_fails
subzy -targets gojekapi.com.txt --hide_fails
subzy -targets gojek.co.id.txt --hide_fails
subzy -targets goldman.com.txt --hide_fails
subzy -targets goldmansachs.com.txt --hide_fails
subzy -targets goldmansachsindices.com.txt --hide_fails
subzy -targets goodrx.com.txt --hide_fails
subzy -targets google.com.txt --hide_fails
subzy -targets grab.careers.txt --hide_fails
subzy -targets grab.com.txt --hide_fails
subzy -targets grab.co.txt --hide_fails
subzy -targets grabpay.com.txt --hide_fails
subzy -targets grabtaxi.com.txt --hide_fails
subzy -targets grammarly.ai.txt --hide_fails
subzy -targets grammarly.com.txt --hide_fails
subzy -targets grammarly.io.txt --hide_fails
subzy -targets grammarly.net.txt --hide_fails
subzy -targets greenhouse.events.txt --hide_fails
subzy -targets greenhouse.io.txt --hide_fails
subzy -targets grepolis.com.txt --hide_fails
subzy -targets grofers.com.txt --hide_fails
subzy -targets growth.org.txt --hide_fails
subzy -targets gsa.gov.txt --hide_fails
subzy -targets gsam.com.txt --hide_fails
subzy -targets gs.com.txt --hide_fails
subzy -targets gspublishing.com.txt --hide_fails
subzy -targets gsselect.com.txt --hide_fails
